# Generated by Django 2.2.4 on 2019-11-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191018_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
    ]
