# Generated by Django 2.2.4 on 2019-11-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_profile_fk_roleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('pk_profile_roleid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_profileid', models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Profile')),
                ('fk_roleid', models.ForeignKey(db_column='fk_roleid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Role')),
            ],
            options={
                'db_table': 'profile_role',
                'managed': True,
            },
        ),
    ]
